var phrases = [
"Early bird gets the worm", 
"Read between the lines", 
"I can eat a horse", 
"Twenty-four seven", 
"Cat got your tounge", 
"One in one million", 
"I beg to differ", 
"Easier said than done", 
"Add insult to injury", 
"Don't cry over spilled milk", 
"Curiosity killed the cat", 
"Two peas in a pod",
"That's the last straw", 
"Piece of cake", 
"Speak of the devil", 
"Go the whole nine yards", 
"An eye for an eye", 
"Hit the hay",
"Stab someone in the back", 
"Quit cold turkey", 
"Cut to the chase",
"Best of both worlds", 
"Kill two birds with one stone", 
"Break a leg", 
"Hit the nail on the head", 
"Kick the bucket"];